### ISSUE TITLE
Change color of circle

### ISSUE THREAD

**Issue by prestomasher** [mikael-desharnais/circliful-reloaded#1]
Hi,

Great work. How can I change the color of the circle programmatically when I update the value like this:

$('#replacement-chart').circliful('animateToValue', parseInt( data.replacementpercent ));

Thanks for your help

**Comment by mikael-desharnais** [comment]
Hi,

I have created some code for this feature. Il will be pushed to github 
as soon as github will be back online.

Regards,

**Comment by prestomasher** [comment]
Great! Thanks. I will be watching for it.

**Comment by prestomasher** [comment]
Hi,

Sorry to insist. Can you upload the code?

**Comment by mikael-desharnais** [comment]
Hi,

Sorry, I didn't send you an email to say it but, my code has been upload 
5 days ago.

You will find an exemple of color change in the index.html file.

Regards,

**Comment by prestomasher** [comment]
Great job! It works beautifully!
