### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by prestomasher** [mikael-desharnais/circliful-reloaded#2]
Is there any destroy mechanism? I didn't see any destroy methods on the code.

**Comment by mikael-desharnais** [comment]
Hi,

at the moment, there is no such mechanism, that should be quite easy to
add, I'm going to look at it and keep you posted.

Regards,

2015-05-11 17:00 GMT+02:00 Jorge Carmona notifications@github.com:

**Comment by mikael-desharnais** [comment]
Hi,

I have added a destroy method.

Regards,

**Comment by prestomasher** [comment]
thanks!

Will this destroy the instance as well?

**Comment by mikael-desharnais** [comment]
Hi,

this destroys the html and the data associated.

Regards

**Comment by prestomasher** [comment]
Hi Mikael,

Thanks for all great support!

I did see that the data and the html was being destroyed. What about the object instance in memory? Should I just do a jQuery $("#myId").remove() ?

Thanks and great work!

**Comment by mikael-desharnais** [comment]
Hi,

all pointers to the object instance in memory are deleted by the destroy 
method so the object should be garbage collected as far as I know.

Regards,

**Comment by prestomasher** [comment]
Great! Thanks again and great work! The chart looks great on my app!
