### ISSUE TITLE
Unable to set "drawer"

### ISSUE THREAD

**Issue by ZephD** [mikael-desharnais/circliful-reloaded#4]
When merging the custom "options" into "settings" (which is a clone of "default settings")
You loop over the custom "options" and check if the value appears in "settings"
Since "drawer" is undefined in the "settings", it does not does get copied from "options"

`for(var i in options){`
`if (typeof this.settings[i] != "undefined"){`
`this.settings[i] = options[i]`
`}`
`}`

**Comment by mikael-desharnais** [comment]
Hi,

thanks, sorry for the delay

This bug is now corrected.

Regards
