### ISSUE TITLE
halfcircl

### ISSUE THREAD

**Issue by gesaleh** [mikael-desharnais/circliful-reloaded#5]
Hi 
when i try to create a half circle the forground circle is badly displayed (it doesn't take inot account that it is hlaf circle

![image](https://cloud.githubusercontent.com/assets/19175308/17754556/624b649e-64d5-11e6-94cd-025fd3a2d93c.png)

![image](https://cloud.githubusercontent.com/assets/19175308/17754572/71f95f72-64d5-11e6-9d83-d775e8e1557a.png)

maybe i'm missing something or an option

i just updated the index.html for testing

```
var value = $('#myStathalf').circliful({
                getText : function(){
                    if (this.usesTotal()){
                        return Math.round(this.getCurrentValue())+" kW";
                    }else {
                        return this.getCurrentValue()+" %";
                    }
                },
                getInfoText : function(){
                    return "Used power";
                },
                "dimension" : 300,
                "max-angle" : 1,
                "start-point": -1,
                "foreground-radius": 90,    
                "display-style" : 'half'
            });
```

**Comment by mikael-desharnais** [comment]
Hi,

this problem is restricted to the SVG support. If you comment the SVG support in the html file :+1: 

`<!--<script src="js/jquery.circliful.svg.js"></script>-->`

It should work fine.

I will have a look as soon as possible at this problem with svg support.

Regards.

**Comment by gesaleh** [comment]
thanks work like a charm

**Comment by mikael-desharnais** [comment]
Hi,

My last commit solves the core of the bug in SVG support.

Regards
